# Site settings
title: web:~ hosain#
email:
description: > # this means to ignore newlines until "baseurl:"
  Programming, travel and photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hosain.net" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
